### config.py

# 게임 설정을 정의

MAX_ATTEMPTS_PER_CATEGORY = 10
CATEGORIES = ['A', 'B', 'C']
INITIAL_SUCCESS_PROB = 0.75
SUCCESS_PROB_CHANGE = 0.1
MIN_SUCCESS_PROB = 0.25
MAX_SUCCESS_PROB = 0.75

WIN_CONDITION_A_B = 7
FAIL_CONDITION_A_B = 4
WIN_CONDITION_C = 4
FAIL_CONDITION_C = 5

TOTAL_STEPS = MAX_ATTEMPTS_PER_CATEGORY * len(CATEGORIES)